INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Piano Kawai GX-2',
    'https://ae01.alicdn.com/kf/HTB1eZEia.T1gK0jSZFhq6yAtVXax/Thu-Nh-Piano-M-H-nh-en-Tr-ng-Ph-m-n-Piano-Mini-Trang-Tr.jpg',
    'Japan',
    'Kawai',
    550000000,
    'Grand piano',
    1,
    'gỗ',
    'trung bình',
    120,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Piano Yamaha U1',
    'https://musictalent.vn/wp-content/uploads/2021/07/up_product_u1_po-ebo_515766315cc831ac24d247b9585d1296.jpg',
    'Japan',
    'Yamaha',
    139000000,
    'Grand piano',
    1,
    'gỗ',
    'trung bình',
    120,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Piano STEINRICH A64',
    'https://pianoart.vn/wp-content/uploads/2019/10/web-01-1.png',
    'Japan',
    'STEINRICH',
    220000000,
    'Grand piano',
    1,
    'gỗ',
    'trung bình',
    120,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Piano Yamaha YDP 143R',
    'https://product.hstatic.net/1000342432/product/yamaha_ydp_143r_2_a48203e5fe4b4163b308d79fe55e213a_master.jpg',
    'Japan',
    'Yamaha',
    189000000,
    'Grand piano',
    1,
    'gỗ',
    'trung bình',
    120,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Piano Samick',
    'https://pianovietthanh.com.vn/uploads/SanPham/b0f0ba28-a9c5-404c-bef0-46573b60c03b.jpg',
    'Japan',
    'Samick',
    165000000,
    'Grand piano',
    1,
    'gỗ',
    'trung bình',
    120,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Piano Stein&son',
    'https://solg.vn/wp-content/uploads/2020/02/solg_Dai-duong-cam.png',
    'Japan',
    'Stein',
    440000000,
    'Grand piano',
    1,
    'gỗ',
    'trung bình',
    120,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Piano Roland GP607',
    'https://pianohouse.vn/image/catalog/products/digital-piano/roland-gp607-1.jpg',
    'Japan',
    'Roland',
    120000000,
    'Grand piano',
    1,
    'gỗ',
    'trung bình',
    120,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Piano Kawai KG3',
    'https://vietthuongshop.vn/upload/content/images/Tuvan/2019/7-2019/mau1-dan-piano-dien-casio-cdp-s100.jpg',
    'Japan',
    'Kawai',
    190000000,
    'Grand piano',
    1,
    'gỗ',
    'trung bình',
    120,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Piano Yamaha G3 Trắng',
    'https://bizweb.dktcdn.net/thumb/grande/100/147/954/products/5-dan-grand-piano-yamaha-trang-g3.jpg?v=1498301995370',
    'Japan',
    'Yamaha',
    170000000,
    'Grand piano',
    1,
    'gỗ',
    'trung bình',
    120,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Piano Upright',
    'https://sovaco.vn/upload/sanpham/pianoyamahau3giare_1606363028_500x416.66666666667.jpg',
    'Japan',
    'Yamaha',
    250000000,
    'Grand piano',
    1,
    'gỗ',
    'trung bình',
    120,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Piano GDP-500 Digital',
    'https://d1aeri3ty3izns.cloudfront.net/media/67/671442/600/preview.jpg',
    'Japan',
    'GDP-500',
    350000000,
    'Grand piano',
    1,
    'gỗ',
    'trung bình',
    120,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Piano Kurtzman KS3',
    'https://tongkhonhaccu.com/Data/upload/images/Product/Piano/Kurtman/ks3/dan-piano-kurztman-ks3-chinh-hang-gia-re.jpg',
    'Japan',
    'Kurtzman',
    378500000,
    'Grand piano',
    1,
    'gỗ',
    'trung bình',
    120,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Piano Điện Yamaha CLP 665 GP',
    'https://nhaccutienmanh.vn/wp-content/uploads/2019/07/dan-piano-dien-yamaha-clavinova-clp-665gp-1.jpg',
    'Japan',
    'Yamaha',
    378500000,
    'Grand piano',
    1,
    'gỗ',
    'trung bình',
    120,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Đàn Piano Điện Yamaha YDP-164 R',
    'https://pianoficus.vn/wp-content/uploads/2021/07/YAMAHA-YDP-164-R-4.jpg?v=1627121682',
    'Japan',
    'Yamaha',
    400500000,
    'Grand piano',
    1,
    'gỗ',
    'trung bình',
    120,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Đàn Piano Steinway & Sons C-227',
    'http://pianominhthanh.vn/upload/product/dan-piano-steinway-c-227iw.png',
    'Japan',
    'Stein',
    221900000,
    'Grand piano',
    1,
    'gỗ',
    'trung bình',
    120,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Đàn Grand Piano Steinway & Sons D-274',
    'https://pianovietthanh.vn/wp-content/uploads/2017/08/1-9.png',
    'Japan',
    'Stein',
    99500000,
    'Grand piano',
    1,
    'gỗ',
    'trung bình',
    120,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Piano Steinway & Sons K-132',
    'http://pianominhthanh.vn/upload/product/dan-piano-steinway-k-132iw.png',
    'Japan',
    'Stein',
    185000000,
    'Grand piano',
    1,
    'gỗ',
    'trung bình',
    120,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Đàn Piano Samick J303E',
    'https://musiccity.vn/wp-content/uploads/2021/06/piano-samick-j303e-limited-edition-musiccity.jpg',
    'Japan',
    'Samick',
    179000000,
    'Grand piano',
    1,
    'gỗ',
    'trung bình',
    120,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Piano Điện Roland LX-705',
    'https://vietthuongshop.vn/image/catalog/2-san-pham/piano/piano-dien/roland/roland-lx-705-8.jpg',
    'Japan',
    'Roland',
    379000000,
    'Grand piano',
    1,
    'gỗ',
    'trung bình',
    120,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Piano điện Roland HP7',
    'https://pianonamphong.com/wp-content/uploads/2021/03/roland-hp-7_95a339f3129d452bb221d64483f0415c_master.jpg',
    'Japan',
    'Roland',
    98000000,
    'Grand piano',
    1,
    'gỗ',
    'trung bình',
    120,
    'none',
    '12 tháng'
);