INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Đàn Ukulele Soprano',
    'https://pianonet.vn/image/cache/catalog/san-pham/Ukulele/%C4%90%C3%A0n%20Ukulele%20Soprano%2021inch%20(Nhi%E1%BB%81u%20M%C3%A0u%20Tr%C6%A1n)/%C4%90%C3%A0n%20Ukulele%20Soprano%2021inch%20Xanh%20pastel-600x600.jpg',
    'USA',
    'Soprano',
    5000000,
    'Dáng tròn',
    4,
    'gỗ',
    'trung bình',
    2,
    'capo',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Ukulele Cordoba Concert UKC-30',
    'https://nhaccutienmanh.vn/wp-content/uploads/2019/07/dan-ukulele-cordoba-concert-ukc-30-1.jpg',
    'USA',
    'Cordoba',
    1100000,
    'Dáng tròn',
    4,
    'gỗ',
    'trung bình',
    2,
    'capo',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Tanglewood TWT1',
    'https://amnhacvietthanh.vn/wp-content/uploads/2020/09/ukulele-Tanglewood-TWT1.jpg',
    'USA',
    'Tanglewood',
    1160000,
    'Dáng tròn',
    4,
    'gỗ',
    'trung bình',
    2,
    'capo',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Ukulele Diana Soprano DS-05/10',
    'https://tongkhonhaccu.com/Data/upload/images/Product/Ukulele/KAKA/soprano/ukulele-diana-soprano-ds-05.jpg',
    'USA',
    'Soprano',
    650000,
    'Dáng tròn',
    4,
    'gỗ',
    'trung bình',
    2,
    'capo',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Ukulele Soprano Mahalo MD1 HABUB',
    'https://product.hstatic.net/1000377468/product/a1_7a655d6fe60047a0a25d9860fc547ae9.jpg',
    'USA',
    'Soprano',
    800000,
    'Dáng tròn',
    4,
    'gỗ',
    'trung bình',
    2,
    'capo',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Tanglewood TWT3',
    'https://amnhacvietthanh.vn/wp-content/uploads/2020/09/ukulele-Tanglewood-TWT3.jpg',
    'USA',
    'Tanglewood',
    1450000,
    'Dáng tròn',
    4,
    'gỗ',
    'trung bình',
    2,
    'capo',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Tanglewood Tiare Concert Ukulele',
    'https://www.dawsons.co.uk/images/20200622091840/ap/resizeandpad:1200:1200/18019/tanglewood-tiare-concert-ukulele-black-walnut-satin.jpg',
    'USA',
    'Tanglewood',
    2000000,
    'Dáng tròn',
    4,
    'gỗ',
    'trung bình',
    2,
    'capo',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Tanglewood TWT3',
    'https://pianonet.vn/image/cache/catalog/san-pham/Ukulele/%C4%90%C3%A0n%20Ukulele%20Soprano%2021inch%20(Nhi%E1%BB%81u%20M%C3%A0u%20Tr%C6%A1n)/%C4%90%C3%A0n%20Ukulele%20Soprano%2021inch%20Xanh%20pastel-600x600.jpg',
    'USA',
    'Tanglewood',
    2500000,
    'Dáng tròn',
    4,
    'gỗ',
    'trung bình',
    2,
    'capo',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Cordoba 20TM Tenor Ukulele',
    'https://images-na.ssl-images-amazon.com/images/I/71SG8rdANXL.jpg',
    'USA',
    'Cordoba',
    7320203,
    'Dáng tròn',
    4,
    'gỗ',
    'trung bình',
    2,
    'capo',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Cordoba 28C Concert Ukulele',
    'https://www.georgesmusic.com/cordoba-28c-MAIN.jpg',
    'USA',
    'Cordoba',
    4070000,
    'Dáng tròn',
    4,
    'gỗ',
    'trung bình',
    2,
    'capo',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Cordoba Protege Ukulele',
    'https://www.bhphotovideo.com/images/images2500x2500/cordoba_03910_u1_protege_ukulele_1321063.jpg',
    'USA',
    'Cordoba',
    1990000,
    'Dáng tròn',
    4,
    'gỗ',
    'trung bình',
    2,
    'capo',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Ukulele Mahalo Soprano U320S/G',
    'https://nhaccutienmanh.vn/wp-content/uploads/2019/07/dan-ukulele-mahalo-soprano-u320s-g-1.jpg',
    'USA',
    'Cordoba',
    1050000,
    'Dáng tròn',
    4,
    'gỗ',
    'trung bình',
    2,
    'capo',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Tanglewood TWT1',
    'https://vietthuongshop.vn/image/catalog/2-san-pham/ukulele/ukulele-tanglewood/dan-ukulele-tanglewood-twt1-1.jpg',
    'USA',
    'Tanglewood',
    1160000,
    'Dáng tròn',
    4,
    'gỗ',
    'trung bình',
    2,
    'capo',
    '12 tháng'
);