INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Yamaha SX600',
    'https://amnhacvietthanh.vn/wp-content/uploads/2020/11/organ-Yamaha-SX600.jpg',
    'Japan',
    'Yamaha',
    19000000,
    'Organ',
    2,
    'gỗ',
    'trung bình',
    26,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Organ Yamaha PSR-E363',
    'https://vn.yamaha.com/vi/files/psr-e363_1080x1080_1080x1080_3b979be49d32729e96049a7488c7cc10.jpg',
    'Japan',
    'Yamaha',
    4410000,
    'Organ',
    2,
    'gỗ',
    'trung bình',
    25,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'ORGAN KURZWEIL KP200',
    'https://tongkhonhaccu.com/Data/upload/images/Product/Organ/KURZWEIL/KP200/dan-organ-kurzweil-kp200-chinh-hang-gia-re.jpg',
    'Japan',
    'Kurzweil',
    7200000,
    'Organ',
    2,
    'gỗ',
    'trung bình',
    25,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Organ Kurzweil KP80',
    'https://product.hstatic.net/200000359259/product/organ-kurzweil-kp80-1_4613af4db3cf4d24ae6ca8c7a171ede0_master.png',
    'Japan',
    'Kurzweil',
    3600000,
    'Organ',
    2,
    'gỗ',
    'trung bình',
    25,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'ORGAN KURTZMAN K250',
    'https://product.hstatic.net/200000359259/product/organ-kurtzman-k250_58aa5c0287b443cabd371dbc4f9293c7.png',
    'Japan',
    'Kurtzman',
    5200000,
    'Organ',
    2,
    'gỗ',
    'trung bình',
    25,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Organ Yamaha PSR-S975',
    'https://hoangpiano.com/resize-image/600x600/organ/dan-organ-yamaha-psr-s975.jpg',
    'Japan',
    'Yamaha',
    29500000,
    'Organ',
    2,
    'gỗ',
    'trung bình',
    25,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Organ Yamaha MOTIF MX61',
    'https://nhaccutienmanh.vn/wp-content/uploads/2019/07/dan-organ-yamaha-motif-mx61-2.jpg',
    'Japan',
    'Yamaha',
    19500000,
    'Organ',
    2,
    'gỗ',
    'trung bình',
    25,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Organ Kurtzman K250',
    'https://salt.tikicdn.com/ts/tmp/de/67/a8/2d1455241a34b3f462a65189ef83a7a0.jpg',
    'Japan',
    'Kurtzman',
    4999000,
    'Organ',
    2,
    'gỗ',
    'trung bình',
    25,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Organ Kurzweil KP100',
    'https://amnhacvietthanh.vn/wp-content/uploads/2020/11/organ-Yamaha-SX600.jpg',
    'Japan',
    'Kurzweil',
    4000000,
    'Organ',
    2,
    'gỗ',
    'trung bình',
    25,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Organ Kurtzman K150',
    'https://bizweb.dktcdn.net/thumb/grande/100/147/954/products/2-3fe97f25-2c3e-48ea-ae27-2e3c58870a77.jpg?v=1594373374977',
    'Japan',
    'Kurtzman',
    2090000,
    'Organ',
    2,
    'gỗ',
    'trung bình',
    25,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Yamaha PSR-E463',
    'https://tuannguyenmusic.com/resource/images/2019/10/yamaha-psr-e-4631.jpg',
    'Japan',
    'Yamaha',
    6990000,
    'Organ',
    2,
    'gỗ',
    'trung bình',
    25,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Yamaha PSR-E273',
    'https://tongkhonhaccu.com/Data/upload/images/Product/Organ/Yamaha/psr-e273/dan-organ-yamaha-psr-e273-chinh-hang-gia-re.jpg',
    'Japan',
    'Yamaha',
    3490000,
    'Organ',
    2,
    'gỗ',
    'trung bình',
    25,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Organ Kurzweil KP80',
    'https://amnhacvietthanh.vn/wp-content/uploads/2020/11/organ-Yamaha-SX600.jpg',
    'Japan',
    'Kurzweil',
    3600000,
    'Organ',
    2,
    'gỗ',
    'trung bình',
    25,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Organ Kurtzman K150',
    'https://tongkhonhaccu.com/Data/upload/images/Product/Organ/Kurtzman/k150/dan-organ-kurtzman-k150-mau-trang-chinh-hang-gia-re.jpg',
    'Japan',
    'Kurtzman',
    2190000,
    'Organ',
    2,
    'gỗ',
    'trung bình',
    25,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Yamaha PSR-EW410',
    'https://hoangpiano.com/resize-image/600x600/organ/dan-organ-yamaha-psr-ew410-6.jpg',
    'Japan',
    'Yamaha',
    10990000,
    'Organ',
    2,
    'gỗ',
    'trung bình',
    25,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'ORGAN KURTZMAN K250',
    'https://product.hstatic.net/200000359259/product/organ-kurtzman-k250_58aa5c0287b443cabd371dbc4f9293c7.png',
    'Japan',
    'Kurtzman',
    5200000,
    'Organ',
    2,
    'gỗ',
    'trung bình',
    25,
    'none',
    '12 tháng'
);
INSERT INTO product (
    name,
    img,
    origin,
    brand,
    price,
    style,
    category,
    material,
    size,
    weight,
    accessories,
    insurance
) VALUES (
    'Organ Kurtzman K300',
    'https://amnhacvietthanh.vn/wp-content/uploads/2020/11/organ-Yamaha-SX600.jpg',
    'Japan',
    'Kurtzman',
    4800000,
    'Organ',
    2,
    'gỗ',
    'trung bình',
    25,
    'none',
    '12 tháng'
);